name: Deploy to GitHub Pages

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master # Branche où on veut déployer
          folder: dist # Dossier qui contient les fichiers statiques générés
          # clean: true # Permet de nettoyer l'historique pour n'avoir que le dernier build
          token: ${{ secrets.GITHUB_TOKEN }}
